image: maven:3.8.6-openjdk-18-slim

cache:
  paths:
    - ./.mvn
  key: "$CI_BUILD_REF_NAME"

stages:
  - build
  - test
  - package

build:
  stage: build
  only:
    - master
    - merge_requests
  script:
    - "mvn clean compile"
  allow_failure: false

test:
  stage: test
  only:
    - master
    - merge_requests
  script:
    - "mvn test"
  allow_failure: false

package:
  stage: package
  only:
    - master
    - merge_requests
  script:
    - "mvn package -DskipTests"
  artifacts:
    paths:
      - "target/*.jar"
    expire_in: 2 week
  allow_failure: false