version: "3.2"
services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
    networks:
      - virtual-school_dev_net
  postgres:
    image: 'postgres:14.4-alpine'
    ports:
      - "5433:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data
  postgres-test:
    image: 'postgres:14.4-alpine'
    ports:
      - "5434:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=postgres'
networks:
  virtual-school_dev_net:
    driver: bridge