server:
  port: 8080
admin:
  login: admin
  pass: admin

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://postgres/postgres
    username: postgres
    password: postgres
  sql:
    init:
      platform: postgres