server:
  port: 8080

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres