server:
  port: 8080
admin:
  login: admin
  pass: admin

spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5434/postgres
    driverClassName: org.postgresql.Driver
    password: postgres
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: 'true'
  sql:
    init:
      platform: postgres