server:
  port: 8080
admin:
  login: admin
  pass: admin

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/postgres
    driverClassName: org.postgresql.Driver
    hikari:
      idle-timeout: 100000
      max-lifetime: 600000
      minimum-idle: 1
      maximum-pool-size: 25