ALTER TABLE teacher ADD COLUMN standing_years INTEGER;
ALTER TABLE teacher ADD COLUMN full_name VARCHAR(255);
ALTER TABLE teacher ADD COLUMN passport VARCHAR(10) UNIQUE;
ALTER TABLE teacher ADD COLUMN snils VARCHAR(14) UNIQUE;